CREATE TABLE IF NOT EXISTS `PagoResumenDiario` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `origen` VARCHAR(30) NOT NULL,
    `referencia_id` INT NOT NULL,
    `cita_id` INT NULL,
    `diagnostico_id` INT NULL,
    `adeudo_id` INT NULL,
    `paciente_id` INT NULL,
    `paciente_nombre` VARCHAR(150) NOT NULL,
    `psicologo_id` INT NULL,
    `psicologo_nombre` VARCHAR(150) NOT NULL,
    `monto` DECIMAL(10,2) NOT NULL,
    `metodo_pago` VARCHAR(50) NOT NULL,
    `fecha_pago` DATETIME NOT NULL,
    `fecha_corte` DATE NOT NULL,
    `registrado_por` INT NULL,
    `observaciones` VARCHAR(255) NULL,
    `creado_en` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_pago_resumen_fecha_corte` (`fecha_corte`),
    KEY `idx_pago_resumen_fecha_pago` (`fecha_pago`),
    KEY `idx_pago_resumen_metodo` (`metodo_pago`),
    KEY `idx_pago_resumen_psicologo` (`psicologo_id`),
    KEY `idx_pago_resumen_paciente` (`paciente_id`),
    KEY `idx_pago_resumen_origen_referencia` (`origen`, `referencia_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
